# Generated by Django 6.0.7 on 2026-08-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frazzetoBookReview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='reviewCount',
        ),
    ]
