# Generated by Django 6.0.7 on 2026-08-02 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frazzetoBookReview', '0002_remove_books_reviewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_review', to='frazzetoBookReview.assignmentreviews'),
        ),
    ]
