# Generated by Django 6.0.7 on 2026-08-02 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frazzetoBookReview', '0003_reviews_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='archived',
        ),
    ]
