# Generated by Django 6.0.7 on 2026-08-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frazzetoBookReview', '0004_remove_courses_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
