# Generated by Django 6.0.7 on 2026-08-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frazzetoBookReview', '0005_alter_authors_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.TextField(),
        ),
    ]
