# Generated by Django 6.0.7 on 2026-08-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frazzetoBookReview', '0006_alter_authors_name_alter_books_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
