# Generated by Django 6.0.7 on 2026-08-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frazzetoBookReview', '0007_books_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='isArchived',
            field=models.BooleanField(default=False),
        ),
    ]
