# Generated by Django 6.0.7 on 2026-08-06 15:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frazzetoBookReview', '0008_courses_isarchived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignmentreviews',
            unique_together={('student', 'course')},
        ),
        migrations.RemoveField(
            model_name='assignmentreviews',
            name='book',
        ),
    ]
